apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: copilot-api
  name: copilot-api
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: copilot-api
  template:
    metadata:
      labels:
        service: copilot-api
    spec:
      nodeSelector:
        kubernetes.io/hostname: rose
      containers:
        - image: ghcr.io/kreatoo/copilot-api-docker:3481c8c
          name: copilot-api
          ports:
            - containerPort: 4141
              protocol: TCP
      restartPolicy: Always
