kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: nginx
  name: nginx-updater
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - 'patch'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: sa-nginx
  namespace: nginx
roleRef:
  kind: Role
  name: nginx
  apiGroup: ""

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-nginx
  namespace: nginx

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-updater
spec:
  # Every week
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-nginx
          containers:
          - name: updater
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment.apps/webserver -n nginx
          restartPolicy: OnFailure
