apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
spec:
  destination:
    namespace: robusta
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://robusta-charts.storage.googleapis.com'
    targetRevision: 0.*
    chart: robusta
    helm:
      valueFiles:
        - generated_values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
