resources:
  - namespace.yaml
  - app.yaml
  - ingressroute.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: nextcloud-db
    namespace: nextcloud
    envs:
      - .env

