# Only restrict access to the database pods, not all pods in the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: protect-mastodon-db
  namespace: mastodon
spec:
  # Select only the database pods
  podSelector:
    matchLabels:
      cnpg.io/cluster: mastodon-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow traffic only from within the same namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mastodon
---
# Allow ingress traffic to application pods from Traefik
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-app
  namespace: mastodon
spec:
  # Select the web and streaming application pods
  podSelector:
    matchExpressions:
      - {key: app, operator: In, values: [web, streaming]}
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow traffic from Traefik namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
---
# Allow cnpg-system full access to database pods (both ingress and egress)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-system-to-db
  namespace: mastodon
spec:
  # Select the database pods
  podSelector:
    matchLabels:
      cnpg.io/cluster: mastodon-db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        # Allow traffic from cnpg-system namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
  egress:
    - to:
        # Allow traffic to cnpg-system namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
