# Only restrict access to the database pods, not all pods in the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: protect-mastodon-db
  namespace: mastodon
spec:
  # Select only the database pods
  podSelector:
    matchLabels:
      cnpg.io/cluster: mastodon-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow traffic from within the same namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mastodon
    - from:
        # Allow traffic from CNPG operator with specific pod selection
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
      ports:
        - port: 8000
        - port: 5432
---
# Allow ingress traffic to application pods from Traefik
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-app
  namespace: mastodon
spec:
  # Select the web and streaming application pods
  podSelector:
    matchExpressions:
      - {key: app, operator: In, values: [web, streaming]}
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow traffic from Traefik namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
