apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
spec:
  project: default
  source:
    chart: valkey
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 2.*
    helm:
      values: |
        auth:
          enabled: false
        replica:
          replicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: mastodon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
