apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: '*'
    chart: traefik
    helm:
      values: |
        deployment:
          replicas: 3

        ports:
          websecure:
            hostPort: 443
            middlewares:
              - traefik-cloudflare@kubernetescrd

        ingressClass:
          enabled: true
          isDefaultClass: true

        additionalArguments:
          - --providers.kubernetescrd.allowCrossNamespace=true
          - --entrypoints.name.http3
          #- --entryPoints.web.forwardedHeaders.insecure
          #- --log.level=DEBUG
          #- --serverstransport.insecureskipverify=true
        
        experimental:
          plugins:
            cloudflaregate:
              moduleName: github.com/sstoner/cloudflaregate
              version: v1.1.2

        tlsStore:
          default:
            defaultCertificate:
              secretName: wildcard-kreato.dev-tls
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
