apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://nextcloud.github.io/helm/'
    targetRevision: 5.*
    chart: nextcloud
    helm:
      values: |
        nextcloud:
          host: "cloud.kreato.dev"
          username: "kreato"
          configs:

            custom.config.php: |-
                <?php
                $CONFIG = array (
                  'overwritehost' => 'cloud.kreato.dev',
                  'overwriteprotocol' => 'https',
                  'overwrite.cli.url' => 'https://cloud.kreato.dev',
                  'filelocking.enabled' => 'true',
                  'loglevel' => '0',
                  'enable_previews' => true,
                  'trusted_domains' =>
                    [
                      'cloud.kreato.dev'
                    ],
                  'maintenance_window_start' => 1,
                  'trusted_proxies' => ['10.43.65.89'],
                  'default_phone_region' => 'tr',
                );


        internalDatabase:
          enabled: false

        externalDatabase:
          enabled: true
          type: mysql
          existingSecret:
            enabled: true
            secretName: nextcloud-db
            usernameKey: mariadb-username
            passwordKey: mariadb-password

        mariadb:
          enabled: true
          auth:
            existingSecret: "nextcloud-db"


          primary:
            persistence:
              enabled: true
          # Use an existing Persistent Volume Claim (must be created ahead of time)
          #existingClaim: nexcloud
          # storageClass: ""
              accessMode: ReadWriteOnce
              size: 16Gi

        #redis:
          #enabled: true
          #auth:
            #enabled: true
            #existingSecret: "nextcloud-db"
            #existingSecretPasswordKey: "redis-password"

        persistence:
          enabled: true
          # Use an existing Persistent Volume Claim (must be created ahead of time)
          #existingClaim: nexcloud
          # storageClass: ""
          accessMode: ReadWriteOnce
          size: 16Gi
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
