apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: answer-postgresql
  namespace: argocd
spec:
  destination:
    namespace: answer
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    chart: postgresql-ha
    targetRevision: '15.*'
    helm:
      values: |
        pgpool:
          configuration: |
            connection_cache = false
            failover_on_backend_error = on
            failover_on_backend_shutdown = on
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
