resources:
  - namespace.yaml
  - app.yaml
secretGenerator:
  - name: op-credentials
    namespace: 1password
    files:
      - 1password-credentials.json
  - name: onepassword-token
    namespace: 1password
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
