resources:
  - namespace.yaml
  - app.yaml
  - configmap.yaml
  - issuer.yaml
  - wildcard-cert.yaml


generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: traefik
    envs:
      - .env
