name: Deploy

on:
  workflow_run:
    workflows: ["YAML Lint"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s-deploy
          version: 1.72.1
          hostname: kreat8s-deploy 
          
      - name: Install kubectl
        uses: Azure/setup-kubectl@v4.0.0

      - name: Install Helm
        uses: Azure/setup-helm@v4.2.0

      - name: Add kubeconfig
        env:
          KUBECTLCONFFULL: ${{ secrets.KUBECONFIG }}
        run: |
            mkdir -p $HOME/.kube
            echo "$KUBECTLCONFFULL" > $HOME/.kube/config

      - name: Run Kustomize
        run: |
          kubectl kustomize --enable-helm | kubectl apply -f - 
