name: Check k0s Version
on:
  schedule:
    # Run daily at 8 AM
    - cron: '0 8 * * *'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  check-k0s-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s-deploy
          version: 1.72.1
          hostname: k0s-version-checker
          
      - name: Install kubectl
        uses: Azure/setup-kubectl@v4
        
      - name: Add kubeconfig
        env:
          KUBECTLCONFFULL: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECTLCONFFULL" > $HOME/.kube/config
          
      - name: Get cluster version
        run: |
          # Get full cluster version
          CLUSTER_VERSION=$(kubectl version -o json | jq -r '.serverVersion.gitVersion')
          echo "Cluster version: $CLUSTER_VERSION"
          echo "CLUSTER_VERSION=$CLUSTER_VERSION" >> $GITHUB_ENV
          
      - name: Get latest k0s version
        run: |
          # Get latest k0s version
          LATEST_K0S_VERSION=$(curl -s https://api.github.com/repos/k0sproject/k0s/releases/latest | jq -r '.tag_name')
          echo "Latest k0s version: $LATEST_K0S_VERSION"
          echo "LATEST_K0S_VERSION=$LATEST_K0S_VERSION" >> $GITHUB_ENV
          
      - name: Check for version mismatch
        id: check_version
        run: |
          # Extract k0s version from gitVersion if available (format: vX.Y.Z+k0s.N)
          if [[ "$CLUSTER_VERSION" == *"+k0s."* ]]; then
            CURRENT_K0S_SEMVER=$(echo "$CLUSTER_VERSION" | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
            CURRENT_K0S_BUILD=$(echo "$CLUSTER_VERSION" | grep -o 'k0s\.[0-9]\+')
            CURRENT_K0S="$CURRENT_K0S_SEMVER+$CURRENT_K0S_BUILD"
            echo "Detected k0s version: $CURRENT_K0S"
          else
            # If not a k0s cluster or can't determine version
            CURRENT_K0S="unknown"
            echo "Unable to determine k0s version from: $CLUSTER_VERSION"
          fi
          
          echo "CURRENT_K0S=$CURRENT_K0S" >> $GITHUB_ENV
          
          # Latest k0s version without 'v' prefix for cleaner display
          LATEST_K0S_CLEAN=${LATEST_K0S_VERSION#v}
          echo "LATEST_K0S_CLEAN=$LATEST_K0S_CLEAN" >> $GITHUB_ENV
          
          # Check if we need to update
          if [[ "$CURRENT_K0S" == "unknown" ]] || [[ "$LATEST_K0S_VERSION" != "$CURRENT_K0S_SEMVER" ]]; then
            echo "Update may be required: Current=$CURRENT_K0S, Latest=$LATEST_K0S_VERSION"
            echo "VERSION_MISMATCH=true" >> $GITHUB_ENV
          else
            echo "k0s version appears to be up to date"
            echo "VERSION_MISMATCH=false" >> $GITHUB_ENV
          fi
          
      - name: Create issue template
        if: env.VERSION_MISMATCH == 'true'
        run: |
          mkdir -p .github
          cat > .github/k0s-update-template.md << EOF
          ---
          title: "⚠️ k0s Update Available: ${{ env.CURRENT_K0S }} → ${{ env.LATEST_K0S_VERSION }}"
          labels: update, k0s, maintenance
          ---
          
          ## k0s Update Available
          
          A new version of k0s is available.
          
          - **Current Cluster Version**: \`${{ env.CLUSTER_VERSION }}\`
          - **Current k0s Version**: \`${{ env.CURRENT_K0S }}\`
          - **Latest k0s Version**: \`${{ env.LATEST_K0S_VERSION }}\`
          
          ### Action Required
          
          Please update k0s to the latest version to ensure security updates and bug fixes are applied.
          
          This issue was automatically created by the k0s Version Check workflow on $(date).
          EOF
          
      - name: Create GitHub issue if version mismatch
        if: env.VERSION_MISMATCH == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/k0s-update-template.md
          update_existing: true
          search_existing: open
