name: YAML Lint

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yamllint
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint

      - name: Validate YAML syntax
        run: |
          find . -type f \( -name "*.yaml" -o -name "*.yml" \) -print0 | xargs -0 yamllint
