name: YAML Format and Lint
on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Format YAML files
        run: |
          find . -type f \( -name "*.yaml" -o -name "*.yml" \) -print0 | xargs -0 yamlfmt -w
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Format YAML files'
          add: '*.yaml *.yml'
